os: linux
dist: bionic
language: node_js
node_js:
  - 12
#- 14
#- 15
services:
  - docker
env:
  global:
    - KSONNET_VERSION: v0.1.12
    - KUBECFG_VERSION: v0.16.0
    - KUBECTL_VERSION: v1.19.2
    - KUBELESS_KAFKA_VERSION: v1.1.0
    - KUBELESS_VERSION: v1.0.7
    - REPO_DOMAIN: serverless
    - REPO_NAME: serverless-kubeless
    - secure: s+L8ndj0uMNwqbLvbHePHeMJw2LI8DdEdcq1vJ98hNwHOWQc2mHVB4utG9EZFkaL+RAZYduldSJqr443d2BugxrkmzhLUlM5vDks+zHeKecwTah2uuaMUXVT/y/cWDDTVp3phqSqWbHBMG6u0ImvTVWHpnkux55S3QJTHevvhdodpO6VDTsJCEB3e1d2hHxi0L9tJrFXzQRpooV8IUuODwKBJyhK4CD7rvu0D1gBgHaUNnNLrCy4YTaFl19q5NdZUtrQDC7rpSPOhFI9CBFX8GiFq6nY3XzFASwq/JtKc3K7OLIC7Wqb6JpuvFhG6S1yhBzp73pnoE9U0Bi+YMa3L+nPoh58dCB2ldNCCCMbx7R6PWq/TwYzLvgZZ7queC2kbvCTrtU6JJfmb0CxmX1fnUIpCsNeyXaPuo4Ly6WJeAID32z79CwMo9NH0uOVTLy3LTrLcEfELhBRL5+WkMvKmXUt8yN/jEIa/H38pQN5Y/AnJ0KznO8RZ2nLhi1cR+xUkxfPVZ22Wr2XkbzJDZih/mZR+5GQBfUHWgpUChK+e8dOhplk+4PZJEO6Myja7ykXBPYtL9CV/Xi+1nQqLmfhyChiES201KusJr1IrFklslzCzgrSH8Dv2yaYUTe/Ub/I3gWIhKOXY66gkpmB6MSBJUfMK3uR4/wYfCvbtBTugsY=
  jobs:
    - MINIKUBE_KUBERNETES_VERSION=v1.14.9
#    - MINIKUBE_KUBERNETES_VERSION=v1.15.11
#    - MINIKUBE_KUBERNETES_VERSION=v1.16.13
#    - MINIKUBE_KUBERNETES_VERSION=v1.17.9
#    - MINIKUBE_KUBERNETES_VERSION=v1.18.9
#    - MINIKUBE_KUBERNETES_VERSION=v1.19.3
install:
  - npm install -g serverless
  - npm install
  - sudo apt-get update && sudo apt-get install -y conntrack
script:
  - npm run lint || travis_terminate 1
  - npm test || travis_terminate 1
  - ./scripts/integration-tests.sh || travis_terminate 1
after_success:
- |
  if [[ "$TRAVIS_BRANCH" == master && \
        "$TRAVIS_PULL_REQUEST" == false && \
        -n "$ACCESS_TOKEN" ]]; then
       ./scripts/release.sh
  fi
deploy:
  provider: npm
  email: kubernetes@bitnami.com
  api_key:
    secure: FRnE09xWf09t1GRPKWVIlnRFmIV7txT6O+rR7w8dnq0NLIgJSd2O8PAm+D7KgMc1TI4Gg4PCF4XDHYPgkBBOFtOKyrcN9djameHK9u98u0RHV4NG+LIvSh6X32HqOT+0YmF4fckFNUsnme/gOJ0dvJpMuNHzCR7rAwPIMu4LG+d1v5WVGq1i5rMqmXpQBtWDIio+nguPtuBIyrWzoEaKJHxGBgdr6+UJ3BW551RB8dvlU0OnBH1YalIvh5+rbw1vMCS0yfIbQSq+NzLUIod7aswWHJx7HJ1HUNvK7RSOMB406dh5/PNjccnvlfMW5RcxYYrp3kB6pTJEuBE/9cUKJwCiuhNulA45oWoo05ITwXGOXLz1xHpIY3xHQJZVUvBJ/WnXplqUGKTGRaQrN13Njclh6KYvzQfMTjlLhoZyUrysqfyDyuzuzneYCPEDmRoh/9Y9J1kRtNLBoXHgRf+ysMFCfTsQW743GbQPlXk8ZD2cQHFn9AKl3nKbhNAwW07A/NU+xDj6JEPYikjn2Nd2bGbWCMR5oJ1sRmTrqYIfSVjYfpn3yt/WwGxxEvNHrz7U69kOtPn/oKY241s/UQdg9U+Vqv8x62GRRE0sCSq9ro2eNwbENBCu9xMO+3iOz8f4/U32NeY0Ij2D0gm2vUBbcZacpfBK72UxR1Gw6fZqT28=
  on:
    tags: true
    repo: serverless/serverless-kubeless
