service:
  name: cert-manager-https

plugins:
  - serverless-kubeless

provider:
  name: kubeless
  hostname: example.com
  runtime: python3.7
  ingress:
    additionalAnnotations:
      kubernetes.io/tls-acme: "true"
    tlsConfig:
      - hosts:
          - "example.com"
        secretName: ingress-example-com-certs

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
