service: hello-http

provider:
  name: kubeless
  runtime: python3.7
  defaultDNSResolution: 'xip.io'

plugins:
  - serverless-kubeless

functions:
  hello-http:
    handler: handler.hello
    events:
      - http:
          path: /hello
